baseURL = "https://burapatis.github.io/mybook1/"
locale = "th-TH"
defaultContentLanguage = "th"
title = "หนังสือของผม"
theme = "hugo-book"

[params]
  BookSection = "chapters"

[markup.goldmark.renderer]
  unsafe = true
